Repository setlife-network/trinary, pull requests merged in 2022-07, with the labels that each got.

#665 Rework UI for Add/Edit Allocation fields
  .env.example
  api/config/credentials.js
  api/handlers/btcPayServer.js
  api/migrations/20220609175823-createRoles.js
  api/migrations/20220613204024-addNewFieldsToRate.js
  api/migrations/20220614155502-modifyTotalExpectedHoursAndHourlyRateDataType.js
  api/models/Rate.js
  api/models/Role.js
  api/models/index.js
  api/modules/budgeting.js
  api/modules/paymentManagement.js
  api/schema/resolvers/PaymentResolver.js
  api/schema/types/RateType.js
  package-lock.json
  package.json
  server.js
  src/components/Advanced.js
  src/components/AllocationAddForm.js
  src/components/AllocationClientSpecifics.js
  src/components/AllocationOverview.js
  src/components/ClientPaymentsManager.js
  src/components/DeletePayment.js
  src/components/EditAllocationRate.js
  src/components/EditPaymentForm.js
  src/components/RateMaxBudgetForm.js
  src/components/RateProratedMonthlyForm.js
  src/operations/mutations/RateMutations.js
  src/operations/queries/AllocationQueries.js
  src/operations/queries/ContributorQueries.js
  src/styles/Advanced.scss
  src/styles/index.scss
Labels: work in progress

#666 Release/1.4
  api/models/Rate.js
  src/components/Advanced.js
  src/components/AllocationAddForm.js
  src/components/AllocationOverview.js
  src/components/EditAllocationRate.js
  src/components/PaymentTile.js
  src/components/RateMaxBudgetForm.js
  src/components/RateProratedMonthlyForm.js
  src/operations/mutations/RateMutations.js
  src/operations/queries/AllocationQueries.js
  src/operations/queries/ContributorQueries.js
  src/styles/Advanced.scss
  src/styles/index.scss
Labels: staging release

#667 Release/1.4
  api/handlers/stripe.js
  api/modules/clientManagement.js
  api/schema/types/ClientType.js
  src/components/ClientEditDialog.js
  src/components/ClientInfo.js
Labels: staging release

#669 Clear cache and packagess
  package-lock.json
Labels: production release

#668 Hotfix/1.4.1
  package-lock.json
Labels: staging release

#675 Hotfix/1.4.2
  api/modules/paymentManagement.js
  package-lock.json
  src/components/AllocationAddForm.js
Labels: production release
